sources:
    - name: SubgraphEthereum721
      handler:
          graphql:
              endpoint: https://gateway-arbitrum.network.thegraph.com/api/<API_KEY>/subgraphs/id/CBf1FtUKFnipwKVm36mHyeMtkuhjmh4KHzY3uWNNq5ow
documents:
    - ./graphql/getAccountCollections.gql
