sources:
    - name: SubgraphEthereum721
      handler:
          graphql:
              endpoint: https://gateway-arbitrum.network.thegraph.com/api/0ab7a83b03a36ac8a536cd8fa19a8ad4/subgraphs/id/CBf1FtUKFnipwKVm36mHyeMtkuhjmh4KHzY3uWNNq5ow
documents:
    - ./graphql/getAccountCollections.gql
